package com.myspace.deposit_retention;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer_Profile implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String ccid;
	private java.lang.String firstName;
	private java.lang.String lastName;

	private java.util.List<com.myspace.deposit_retention.Account> account;

	public Customer_Profile() {
	}

	public java.lang.String getCcid() {
		return this.ccid;
	}

	public void setCcid(java.lang.String ccid) {
		this.ccid = ccid;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.util.List<com.myspace.deposit_retention.Account> getAccount() {
		return this.account;
	}

	public void setAccount(
			java.util.List<com.myspace.deposit_retention.Account> account) {
		this.account = account;
	}

	public Customer_Profile(java.lang.String ccid, java.lang.String firstName,
			java.lang.String lastName,
			java.util.List<com.myspace.deposit_retention.Account> account) {
		this.ccid = ccid;
		this.firstName = firstName;
		this.lastName = lastName;
		this.account = account;
	}

}