package com.myspace.deposit_retention;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CUSTOMER_PROFILE implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CUSTOMER_PROFILE() {
    }




}