package com.myspace.deposit_retention;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OFFER implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OFFER() {
    }




}