package com.myspace.deposit_retention;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OFFER implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String OFFER_NAME;

	private java.lang.String offerDesc;

	public OFFER() {
	}

	public java.lang.String getOFFER_NAME() {
		return this.OFFER_NAME;
	}

	public void setOFFER_NAME(java.lang.String OFFER_NAME) {
		this.OFFER_NAME = OFFER_NAME;
	}

	public java.lang.String getOfferDesc() {
		return this.offerDesc;
	}

	public void setOfferDesc(java.lang.String offerDesc) {
		this.offerDesc = offerDesc;
	}

	public OFFER(java.lang.String OFFER_NAME, java.lang.String offerDesc) {
		this.OFFER_NAME = OFFER_NAME;
		this.offerDesc = offerDesc;
	}
	
	public boolean equals(Object obj) 
    {
        OFFER offer = (OFFER)obj;
        return offer.getOFFER_NAME().equals(this.getOFFER_NAME());
    }
    public int hashCode() 
    {
     return 1;   
    }

}